# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import main.base_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('type', models.CharField(blank=True, choices=[('EG', 'Eyeglasses'), ('SG', 'Sunglasses')], default='', max_length=3)),
                ('category', models.CharField(blank=True, choices=[('MN', 'Men'), ('WM', 'Women'), ('KD', 'Kids')], default='', max_length=3)),
                ('model_number', models.CharField(blank=True, default='', max_length=300)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('frame_type', models.CharField(blank=True, default='', max_length=300)),
                ('lens_size', models.PositiveIntegerField(blank=True, default=0)),
                ('image_url', models.URLField(blank=True, default='')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
            bases=(main.base_models.BaseProduct, models.Model),
        ),
    ]
