# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('content', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.Product')),
            ],
            options={
                'ordering': ('created',),
                'abstract': False,
            },
        ),
    ]
