# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-22 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200922_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_qty',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Available quantity'),
        ),
    ]
