# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-09-30 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200922_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frame_type',
            field=models.CharField(blank=True, choices=[('RA', 'Rectangle Frames'), ('RN', 'Round Frames'), ('SQ', 'Square Frames'), ('RM', 'Rimless Frames')], default='', max_length=2),
        ),
    ]
