# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201014_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
