# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_is_top_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=300, unique=True),
        ),
    ]
