# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201018_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
