# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-10-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201030_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
