# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-11-03 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201103_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.FrameType'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.ProductType'),
        ),
    ]
